services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    user: root
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /data
    volumes:
      - ./data/dynamodb:/data
    ports:
      - "8000:8000"
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:8000 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  dynamodb-init:
    depends_on:
      dynamodb-local:
        condition: service_healthy
    image: amazon/aws-cli:latest
    environment:
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      AWS_DEFAULT_REGION: us-east-1
    entrypoint: >
      /bin/sh -c "aws dynamodb create-table --table-name memo --attribute-definitions AttributeName=id,AttributeType=S --key-schema AttributeName=id,KeyType=HASH --billing-mode PAY_PER_REQUEST --endpoint-url http://dynamodb-local:8000 --region us-east-1"

  dynamo-admin:
    image: aaronshaf/dynamodb-admin:latest
    container_name: dynamo-admin
    environment:
      DYNAMO_ENDPOINT: http://dynamodb-local:8000/
    ports:
      - "8001:8001"
    depends_on:
      - dynamodb-local

networks:
  local-net:
    driver: bridge

volumes:
    db: