package com.around40engineer.backend

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable

@DynamoDBTable(tableName = "memo")
class MemoEntity(
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    var id: String? = null,

    @DynamoDBAttribute
    var memo: String = ""
)
